### PR TITLE
Build with webpack

### PR DESCRIPTION
**Pull request by liliakai**
Use webpack to bundle and package extension files, based on https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate. This removes the project's dependency on browserify and builds an *almost* identical .zip to the old build system. 

Changes of note:
 * Directory structure: Source files have all moved to /src. Everything outside src should be package-level metadata or build/toolchain-related.
 * `webpack.config.js` defines all bundling and copying operations. It outputs files into a `/build` directory for packaging. The `Makefile` is greatly simplified as a result, and could be eliminated entirely if desired.
 * The packaged copy of `manifest.json` is minified and its `description` and `version` fields are copied automatically from `package.json`. The ones defined in `src/manifest.json` itself are now ignored and could be removed or commented out as such. Let me know if this is not preferred behavior - it came with the boilerplate but is easy to change.
* The build is now `NODE_ENV`-sensitive, defaulting to a `development` build. Bundled files (`gmail.js`, `domains.js`, `gui.js`) are minified when `NODE_ENV=production`, for instance.
* A content security policy is injected into the packaged copy of `manifest.json` to enable `unsafe-eval` for webpack (but only in a development build).

Bonus for developers!
* Automatic extension rebuild/reloading! Run `[npm|yarn] start` and load the unpacked extension from /build. Then just refresh popup/options page/etc to pick up changes.

This could probably use some more testing and quality assurance, but seems to pass basic smoke testing in chrome + gmail. From here we could further leverage webpack's various file loaders to optimize more of the css, js, and other files in the production build, but for the sake of the reviewer, I've attempted to minimize the effective changes to the build output.

Did I miss anything, break something, or mess up any workflows? Any and all feedback is quite welcome.

### CODE REVIEW

**Comment by botherder** [comment]
Thank you. I'll go through and testing it hopefully tomorrow.
As a side note: would you be able to use 4-spaces indentation? Just so to remain consistent with the rest of the codebase.

**Comment by botherder** [comment]
I built it and ran it, and it seems to work fine. If you are ok with it, I can merge already.

**Comment by liliakai** [comment]
I'll squash the commits to keep the history cleaner, then :+1:.

**Comment by botherder** [comment]
Ok, I'll wait for your :+1: before proceeding.

**Comment by liliakai** [comment]
:+1: Good to go.

**Pull request merged**
